USE master;
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD = '<PASSWORD>';
GO

CREATE CERTIFICATE TDE_CERT
WITH SUBJECT = 'TDE_CERT'
GO

USE Library;
GO

CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE TDE_CERT;
GO

ALTER DATABASE Library
SET ENCRYPTION ON
GO